# Generated by Django 5.1.7 on 2025-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiffreaffaire',
            name='chiffre_affaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
